version: "3.6"

services:
  supportkiosk:
    container_name: "supportkiosk"
    image: ghcr.io/kth-biblioteket/supportkiosk:${REPO_TYPE}
    restart: "always"
    env_file:
      - supportkiosk.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.supportkiosk.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`${PATHPREFIX}`)"
      - "traefik.http.routers.supportkiosk.entrypoints=websecure"
      - "traefik.http.routers.supportkiosk.tls=true"
      - "traefik.http.routers.supportkiosk.tls.certresolver=myresolver"
    volumes:
      - /local/docker/supportkiosk/custom.js:/usr/share/nginx/html/supportkiosk/script/custom.js 
    networks:
      - "apps-net"

networks:
  apps-net:
    external: true